apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.clusterSecretStore.provider.vault.server | quote }}
      path: {{ .Values.clusterSecretStore.provider.vault.path | quote }}
      version: {{ .Values.clusterSecretStore.provider.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.clusterSecretStore.provider.vault.tokenSecretRef.name | quote }}
          namespace: {{ .Values.clusterSecretStore.provider.vault.tokenSecretRef.namespace | quote }}
          key: {{ .Values.clusterSecretStore.provider.vault.tokenSecretRef.key | quote }}