apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  refreshInterval: "{{ .Values.externalSecret.refreshInterval }}"
  secretStoreRef:
    name: {{ .Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretKey }}
