apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "db.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "db.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.postgres.nodeSelector | nindent 8 }}
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: {{ .Values.postgres.secretName }}
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
