apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "db.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
