apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  postgres_port: "{{ .Values.application.postgresql.port }}"
  postgres_host: "{{ .Values.application.postgresql.host }}"
  port: "{{ .Values.application.port }}"