
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.application.service.type }}
  selector:
    app: {{ .Values.application.name }}
  ports:
    - port: {{ .Values.application.service.port }}
      targetPort: {{ .Values.application.port }}
      {{- if eq .Values.application.service.type "NodePort" }}
      nodePort: {{ .Values.application.service.nodePort }}
      {{- end }}